apiVersion: v1
kind: List
metadata: {}
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: vultr-status-exporter
      name: vultr-status-exporter
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: vultr-status-exporter
      template:
        metadata:
          labels:
            app: vultr-status-exporter
        spec:
          containers:
            - name: vultr-status-exporter
              image: ghcr.io/dazwilkin/vultr-status-exporter:fbe83c8dfc1abdaf8c61635c9affdd6dab92c5b4
              command:
              - /vultr-status-exporter
              args:
              - --endpoint=:8080
              - --path=/metrics
              ports:
                - name: metrics
                  containerPort: 8080
          restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: vultr-status-exporter
      name: vultr-status-exporter
    spec:
      selector:
        app: vultr-status-exporter
      ports:
        - name: metrics
          port: 8080
          targetPort: 8080
      type: NodePort
  - kind: ServiceMonitor
    apiVersion: monitoring.coreos.com/v1
    metadata:
      name: vultr-status-exporter
      labels:
        app: vultr-status-exporter
    spec:
      selector:
        matchLabels:
          app: vultr-status-exporter
      endpoints:
        - port: metrics